# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 270b24cf09420a5a4341b456142682a1cbadcb8b8c2db3e5313e7def27862f4c4587ccdfb8cb51db8592f1b79c8c5597affcb10c18aa64c9316778045efca11e

test:
  secret_key_base: 8e3809b692010860dbc949020c0d1f1d28c158aeeabd43a4b69904652959d4d002b2a99672c7b2662d38d0243f1e90768e8e7e8b7719b029f7a85ceac9f6a635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
